image: python:latest
before_script:
  - python --version

test:
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update && apt install -y --no-install-recommends pylint
    - pylint --disable=C0114,C0115,C0116 main.py

